name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master

      - uses: actions/checkout@v2

      - run: zig env
      - run: zig build test
